package gui;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;

import java.io.IOException;
import java.util.Optional;
import java.util.ResourceBundle;

import domein.DomeinController;
import exceptions.VoegSpelbordToeException;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.control.Label;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.ButtonBar.ButtonData;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.GridPane;
import javafx.stage.Stage;

public class WijzigSpelbordPaneelController extends GridPane{
	@FXML
	private Label lblSpelbord;
	@FXML
	private GridPane gpSpelbord;
	@FXML
	private Label lblInstructies;
	@FXML
	private Button btnMuur;
	@FXML
	private Button btnKist;
	@FXML
	private Button btnDoel;
	@FXML
	private Button btnMannetje;
	@FXML
	private Button btnLeeg;
	@FXML
	private Button btnKlaar;
	@FXML
	private Button btnHoofdMenu;
	
	private int actie;

	private final DomeinController dc;
	private final ResourceBundle rb;
	
	public WijzigSpelbordPaneelController(DomeinController dc, ResourceBundle rb) {

		super();
		
		this.dc = dc;
		this.rb = rb;
		

		FXMLLoader loader = new FXMLLoader(getClass().getResource("WijzigSpelbordPaneel.fxml"));
		loader.setRoot(this);
		loader.setController(this);
		try {
			loader.load();
		} catch (IOException ex) {
			System.out.println(ex.getMessage());
		}				
		lblSpelbord.setText(dc.geefSpelbordNaam());

		btnMuur.setText(rb.getString("Muur"));
		btnMuur.fire();
		btnKist.setText(rb.getString("Kist"));
		btnDoel.setText(rb.getString("Doel"));
		btnMannetje.setText(rb.getString("Mannetje"));
		btnLeeg.setText(rb.getString("Leeg"));
		btnKlaar.setText(rb.getString("Klaar"));
		btnHoofdMenu.setText(rb.getString("Hoofdmenu"));
	

		lblInstructies.setText(rb.getString("Instructies_spelbord_wijzigen"));

		weergaveSpelbord();
	}
	
	// Event Listener on Button[#btnMuur].onAction
	@FXML
	
	private void weergaveSpelbord() {
		char[][] spelbord = dc.geefWeergaveSpelbord();
		int veldRij = 0;
		int veldKolom = 0;

		for (char[] rij : spelbord) {
			for (char veld : rij) {
				ImageView imgVeld = new ImageView(new Image(
						getClass().getResourceAsStream(String.format("/images/%s.png", veld)), 25, 25, true, false));

				gpSpelbord.add(imgVeld, veldKolom, veldRij);
				imgVeld.addEventHandler(MouseEvent.MOUSE_CLICKED, new EventHandler<MouseEvent>() {

					@Override
					public void handle(MouseEvent event) {
						dc.pasVeldAan(gpSpelbord.getColumnIndex((ImageView) event.getSource()),
								gpSpelbord.getRowIndex((ImageView) event.getSource()), actie);
						weergaveSpelbord();
						event.consume();
					}
				});

				veldKolom++;
			}
			veldRij++;
			veldKolom = 0;
		}

	}
	
	
	public void btnKlaarAfhandeling(ActionEvent event) {
		// TODO Autogenerated

		try {
			dc.valideerSpelbord();
			dc.registreerGewijzigdSpel();

			Alert alert = new Alert(AlertType.CONFIRMATION);
			alert.setTitle("");
			alert.setHeaderText(rb.getString("Spelbord_gewijzigd"));
			alert.setContentText(rb.getString("Wilt_u_nog_een_spelbord_wijzigen?"));
			
			Optional<ButtonType> result = alert.showAndWait();
			if (result.get() == ButtonType.OK) {
				// Nieuw spelbord maken
				Stage stage = (Stage) this.getScene().getWindow();
				Scene scene = new Scene(new KeuzeSpelbordOmTeWijzigenPaneelController(dc, rb));
				stage.setScene(scene);

			} else {
				registreerWijzigenSpel();
				hoofdmenuOproepen();
			}

		} catch (VoegSpelbordToeException e) {
			Alert alert = new Alert(AlertType.CONFIRMATION);
			alert.setTitle("");
			alert.setHeaderText(e.getMessage());

			alert.setContentText(rb.getString("Wat_wilt_u_doen_met_dit_ongeldige_spelbord?"));

			ButtonType verderAanpassen = new ButtonType(rb.getString("Verder_aanpassen"), ButtonData.YES);
			ButtonType verwerpen = new ButtonType(rb.getString("Verwerpen"), ButtonData.NO);
			alert.getButtonTypes().setAll(verderAanpassen, verwerpen);

			Optional<ButtonType> result = alert.showAndWait();
			if (result.get() == ButtonType.YES) {
				alert.close();
			} else {
				// Spelbord verwerpen
				// melding

				registreerWijzigenSpel(); 
				hoofdmenuOproepen();
			}

		}

	}
	
	private void registreerWijzigenSpel() {
		// Spel registreren in DB
		try {
			// TODO Systeem valideert volgens DR_SPEL
			// Systeem geeft gepaste melding
			// Vraagt of een spelbord wil toevoegen aan het spel of wil stoppen
			dc.registreerGewijzigdSpel();

			Alert alert = new Alert(AlertType.INFORMATION);
			alert.setTitle("");
			
			alert.setContentText(rb.getString("Aantal_spelborden") + dc.geefInfoSpel()[1]);
			alert.setContentText("Aantal_spelborden" + dc.geefInfoSpel()[1]);

		} catch (VoegSpelbordToeException e) {
			System.out.println(e.getMessage());
		}

	}

	private void hoofdmenuOproepen() {
		Stage stage = (Stage) this.getScene().getWindow();
		Scene scene = new Scene(new HoofdMenuPaneelController(dc, rb));
		stage.setScene(scene);
	}

	// Event Listener on Button[#btnHoofdMenu].onAction
	@FXML
	public void btnHoofdMenuAfhandeling(ActionEvent event) {
		hoofdmenuOproepen();
	}
	
	public void btnMuurAfhandeling(ActionEvent event) {
		// TODO Autogenerated
		this.actie = 1;
	}

	// Event Listener on Button[#btnKist].onAction
	@FXML
	public void btnKistAfhandeling(ActionEvent event) {
		this.actie = 2;
	}

	// Event Listener on Button[#btnDoel].onAction
	@FXML
	public void btnDoelAfhandeling(ActionEvent event) {
		this.actie = 3;
	}

	// Event Listener on Button[#btnMannetje].onAction
	@FXML
	public void btnMannetjeAfhandeling(ActionEvent event) {
		this.actie = 4;
	}

	// Event Listener on Button[#btnLeeg].onAction
	@FXML
	public void btnLeegAfhandeling(ActionEvent event) {
		this.actie = 5;
	}
}
